### PR TITLE
CDAP-15548 MySQL db plugin enhancements: all data types support and proper test coverage

### PR DESCRIPTION
**Pull request by vladhlinskiy**
JIRA: https://issues.cask.co/browse/CDAP-15548
WIKI: https://wiki.cask.co/display/CE/MySQL+database+plugin

In scope of this PR:

* MySQL datatypes covered by tests

### CODE REVIEW

**Comment by vladhlinskiy** [comment]
@albertshau could you, please, take a look?

**Review by albertshau — APPROVED** [review]
lgtm

**Comment by albertshau** [comment]
lgtm but there are merge conflicts. Please resolve and I'll merge.

**Comment by vladhlinskiy** [comment]
Resolved conflicts, squashed and slightly changed Sink test to avoid duplication. Please, merge, if it's ok.

**Pull request merged**
