### PR TITLE
[PLUGIN-1642] e2e_mysql hook changes

### PR DESCRIPTION
**Pull request by itsmekumari**
e2e MySql Hook Changes @MrRahulSharma @itsankit-google 
cc @Vipinofficial11

### CODE REVIEW

**Review by itsankit-google — COMMENTED** [review]
Can we please add logging to all the test setup hooks? For example: https://github.com/data-integrations/google-cloud/blob/0fe25fee9cea2b608b1e3fa8b01a103741aa7387/src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java#L233

**Comment by itsankit-google** [comment]
To fix build failures, please rebase the PR with develop branch, fixed in #417.

**Comment by itsmekumari** [comment]
> Can we please add logging to all the test setup hooks? For example: https://github.com/data-integrations/google-cloud/blob/0fe25fee9cea2b608b1e3fa8b01a103741aa7387/src/e2e-test/java/io/cdap/plugin/common/stepsdesign/TestSetupHooks.java#L233

Done.

**Comment by itsmekumari** [comment]
> To fix build failures, please rebase the PR with develop branch, fixed in #417.

Done.

**Review by itsankit-google — APPROVED** [review]

**Comment by itsankit-google** [comment]
Please squash commits before merge.

**Pull request merged**
